--STRING & DATE 
--51384
SELECT
    USER_ID,
    NICKNAME,
    CONCAT(CITY,' ',STREET_ADDRESS1,' ',STREET_ADDRESS2) AS '전체주소',
    CONCAT(SUBSTR(TLNO,1,3),'-',SUBSTR(TLNO,4,4),'-',SUBSTR(TLNO,8,4)) AS '전화번호'
FROM
    USED_GOODS_USER
WHERE
    USER_ID IN
            (
            SELECT
                WRITER_ID
            FROM 
                USED_GOODS_BOARD
            GROUP BY
                WRITER_ID
            HAVING
                COUNT(*) >= 3
            )
ORDER BY
    USER_ID DES
--59046
--MYSQL&ORACLE
SELECT ANIMAL_ID, NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS
WHERE NAME IN ('Lucy', 'Ella', 'Pickle', 'Rogan', 'Sabrina', 'Mitty')
ORDER BY ANIMAL_ID;

--59047
--MYSQL
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE NAME LIKE "%el%" AND ANIMAL_TYPE = "DOG"
ORDER BY NAME

--ORACLE
 SELECT ANIMAL_ID,NAME FROM ANIMAL_INS
 WHERE LOWER(NAME) LIKE '%el%'AND ANIMAL_TYPE = 'Dog'
 ORDER BY NAME

--59409
--ORACLE
SELECT ANIMAL_ID, NAME, 
    CASE WHEN SEX_UPON_INTAKE LIKE'Neutered%'OR SEX_UPON_INTAKE LIKE'Spayed%'
    THEN 'O' ELSE 'X' END AS "중성화" FROM ANIMAL_INS
ORDER BY ANIMAL_ID

--59414
--ORACLE
SELECT ANIMAL_ID, NAME,TO_CHAR(DATETIME,'YYYY-MM-DD') AS"날짜"
FROM ANIMAL_INS
ORDER BY ANIMAL_ID
--MYSQL
SELECT ANIMAL_ID, NAME, DATE_FORMAT(DATETIME,'%Y-%m-%d') 
FROM ANIMAL_INS
ORDER BY ANIMAL_ID

--131529
--MYSQL
SELECT LEFT(product_code, 2), COUNT(*) AS PRODUCTs  FROM product
GROUP BY 1;
--ORACLE
SELECT SUBSTR(PRODUCT_CODE,0,2) AS CATEGORY, COUNT(PRODUCT_ID) AS PRODUCTS
FROM PRODUCT
GROUP BY SUBSTR(PRODUCT_CODE,0,2)
ORDER BY SUBSTR(PRODUCT_CODE,0,2)

--131113
--MYSQL
SELECT ORDER_ID,PRODUCT_ID,DATE_FORMAT(OUT_DATE,'%Y-%m-%d') AS OUT_DATE,
    CASE WHEN DATE_FORMAT(OUT_DATE,'%Y-%m-%d')<='2022-05-01' THEN '출고완료'
        WHEN DATE_FORMAT(OUT_DATE,'%Y-%m-%d')>'2022-05-01' THEN '출고대기'
        ELSE '출고미정'
        END AS '출고여부'
FROM FOOD_ORDER
ORDER BY ORDER_ID
--ORACLE
SELECT ORDER_ID,PRODUCT_ID,NVL(TO_CHAR(OUT_DATE,'YYYY-MM-DD'),'') AS OUT_DATE,
    CASE WHEN TO_CHAR(OUT_DATE,'YYYY-MM-DD')<='2022-05-01' THEN '출고완료'
        WHEN TO_CHAR(OUT_DATE,'YYYY-MM-DD')>'2022-05-01' THEN '출고대기'
        ELSE '출고미정'
        END AS "출고여부"
FROM FOOD_ORDER
ORDER BY ORDER_ID
--151138
--MYSQL
SELECT HISTORY_ID, CAR_ID,DATE_FORMAT(START_DATE,'%Y-%m-%d') AS START_DATE,DATE_FORMAT(END_DATE,'%Y-%m-%d')
AS END_DATE,CASE 
    WHEN DATEDIFF(END_DATE,START_DATE)+1 >= 30 THEN "장기 대여"
    ELSE "단기 대여"
    END AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(START_DATE,"%Y-%m") = '2022-09' 
ORDER BY HISTORY_ID DESC

--ORACLE
SELECT HISTORY_ID, CAR_ID,TO_CHAR(START_DATE,'YYYY-MM-DD') START_DATE,TO_CHAR(END_DATE,'YYYY-MM-DD') END_DATE
,CASE WHEN TO_NUMBER(TO_CHAR(END_DATE-START_DATE+1)) >= 30 THEN '장기 대여'ELSE '단기 대여'END  AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE TO_CHAR(START_DATE,'YYYY-MM') ='2022-09'
ORDER BY HISTORY_ID DESC

--157342
--MYSQL
SELECT CAR_ID,ROUND(AVG(DATEDIFF(END_DATE,START_DATE)+1), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION>=7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;

--ORACLE
SELECT CAR_ID,ROUND(AVG(END_DATE-START_DATE)+1,1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING ROUND(AVG(END_DATE-START_DATE)+1,1)>=7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC

--157343
--MYSQL&ORACLE
SELECT CAR_ID, CAR_TYPE, DAILY_FEE, OPTIONS
FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS LIKE '%네비게이션%'
ORDER BY CAR_ID DESC

--164672
--MYSQL
SELECT BOARD_ID, WRITER_ID, TITLE, PRICE, REPLACE(REPLACE(REPLACE(STATUS,'DONE','거래완료'),'SALE','판매중'),'RESERVED','예약중') AS STATUS
FROM USED_GOODS_BOARD
WHERE CREATED_DATE LIKE'2022-10-05'
ORDER BY BOARD_ID DESC

--ORACLE
SELECT BOARD_ID, WRITER_ID, TITLE, PRICE, REPLACE(REPLACE(REPLACE(STATUS,'DONE','거래완료'),'SALE','판매중'),'RESERVED','예약중') AS STATUS
FROM USED_GOODS_BOARD
WHERE TO_CHAR(CREATED_DATE,'YYYY-MM-DD') = '2022-10-05'
ORDER BY BOARD_ID DESC
