--59046
--MYSQL&ORACLE
SELECT ANIMAL_ID, NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS
WHERE NAME IN ('Lucy', 'Ella', 'Pickle', 'Rogan', 'Sabrina', 'Mitty')
ORDER BY ANIMAL_ID;

--151138
--MYSQL
SELECT HISTORY_ID, CAR_ID,DATE_FORMAT(START_DATE,'%Y-%m-%d') AS START_DATE,DATE_FORMAT(END_DATE,'%Y-%m-%d')
AS END_DATE,CASE 
    WHEN DATEDIFF(END_DATE,START_DATE)+1 >= 30 THEN "장기 대여"
    ELSE "단기 대여"
    END AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(START_DATE,"%Y-%m") = '2022-09' 
ORDER BY HISTORY_ID DESC

--ORACLE
SELECT HISTORY_ID, CAR_ID,TO_CHAR(START_DATE,'YYYY-MM-DD') START_DATE,TO_CHAR(END_DATE,'YYYY-MM-DD') END_DATE
,CASE WHEN TO_NUMBER(TO_CHAR(END_DATE-START_DATE+1)) >= 30 THEN '장기 대여'ELSE '단기 대여'END  AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE TO_CHAR(START_DATE,'YYYY-MM') ='2022-09'
ORDER BY HISTORY_ID DESC

--157342
--MYSQL
SELECT CAR_ID,ROUND(AVG(DATEDIFF(END_DATE,START_DATE)+1), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION>=7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;

--ORACLE
SELECT CAR_ID,ROUND(AVG(END_DATE-START_DATE)+1,1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING ROUND(AVG(END_DATE-START_DATE)+1,1)>=7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC

--157343
--MYSQL&ORACLE
SELECT CAR_ID, CAR_TYPE, DAILY_FEE, OPTIONS
FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS LIKE '%네비게이션%'
ORDER BY CAR_ID DESC

--164672
--MYSQL
SELECT BOARD_ID, WRITER_ID, TITLE, PRICE, REPLACE(REPLACE(REPLACE(STATUS,'DONE','거래완료'),'SALE','판매중'),'RESERVED','예약중') AS STATUS
FROM USED_GOODS_BOARD
WHERE CREATED_DATE LIKE'2022-10-05'
ORDER BY BOARD_ID DESC

--ORACLE
SELECT BOARD_ID, WRITER_ID, TITLE, PRICE, REPLACE(REPLACE(REPLACE(STATUS,'DONE','거래완료'),'SALE','판매중'),'RESERVED','예약중') AS STATUS
FROM USED_GOODS_BOARD
WHERE TO_CHAR(CREATED_DATE,'YYYY-MM-DD') = '2022-10-05'
ORDER BY BOARD_ID DESC
